- name: my first playbook
  hosts: all
  gather_facts: true
  tasks:
    - debug: 
        msg: I love Apple
    - debug: 
        msg: I love Straberry
    - debug: 
        msg: I love Banana
    - debug: 
        msg: I love 
    - debug: 
        msg: I love                